version: '3'
services:

  vilnius-app-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: digitalocean.com/php
    container_name: vilnius-app-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ".:/var/www"
      - "./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
    networks:
      - vilnius-network

  nginx:
    image: nginx:alpine
    container_name: vilnius-app-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ".:/var/www"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - vilnius-network

networks:
  vilnius-network:
    driver: bridge